### ISSUE TITLE
fabs creates binning bug when tolerance_in_ppm is True

### ISSUE THREAD

**Issue by RogerGinBer** [prafols/rMSI2#6]
Hi Pere,

This fabs call in line 75 of the binning makes `minMassDistance` be always positive, which in turn makes the bin always insert after the current minDistanceIndex (even if the actual distance is negative)
https://github.com/prafols/rMSI2/blob/08d79480a3b119da96b0638c6db664125994c7ee/src/peakbinning.cpp#L73-L78
https://github.com/prafols/rMSI2/blob/08d79480a3b119da96b0638c6db664125994c7ee/src/peakbinning.cpp#L101-L110

Running some debug tests, this clearly has a **huge** impact on the resulting data structures and total runtime:

![image](https://github.com/prafols/rMSI2/assets/45530914/2f058c62-36c4-442c-a190-d34da213660f)

**Comment by prafols** [comment]
I've just checked it, I agree it was a mistake. Fixed
